# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_YH0mgSOeZphuOoBT4D-_f5wfbDLne4R
"""



executar = True
while executar :




  opcoes ='''
  Esolha abaixo as possíveis operações ->
  
  > [0] ou [+] Para somar 
  > [1] ou [-] Para subtrair
  > [2] ou [/] Para divisão 
  > [3] ou [*] Para multiplicação  
  > [4] ou [^] Para potência 
  > [5] ou [**] Para exponenciação 
  > [6] Para sair

  (ou digite sua opção: Somar / Subtrair / Multiplicar / Dividir / Potenciar/ Elevar /Sair)
  '''

  print(opcoes)
  operador = input('Escolha sua opção ')
  valor01 = input('Escolha seu primeiro valor ')
  valor02 = input('Escolha seu segundo valor ')
  valor01 = int(valor01)
  valor02 = int(valor02)

  
  
  
  #SOMA

  if operador == '0'or operador == '+' or operador == 'Somar'  or operador == 'somar':
    resultado = valor01 + valor02
    print('O resultado é: ' + str(resultado))  

  #SUBTRAÇÃO

  if operador == '1'or operador == '-' or operador == 'Subtrair'  or operador == 'subtrair':
    resultado = valor01 - valor02
    print('O resultado é: ' + str(resultado))
  
  #DIVISÃO

  if operador == '2'or operador == '/' or operador == 'Dividir' or operador == 'dividir':
    resultado = valor01 / valor02
    print('O resultado é: ' + str(resultado))

  #MULTIPLICAÇÃO

  if operador == '3' or operador == '*' or operador == 'Multiplicar' or operador == 'multiplicar':
    resultado = valor01 * valor02
    print('O resultado é: ' + str(resultado))

  #POTENCIAÇÃO

  if operador == '4' or operador == '^' or operador == 'Potenciar'  or operador == 'potenciar':
    resultado = valor01 ^ valor02
    print('O resultado é: ' + str(resultado))

  #EXPONENCIAÇÃO

  if operador == '5' or operador == '**' or operador == 'Elevar' or operador == 'elevar':
    resultado = valor01 ** valor02
    print('O resultado é: ' + str(resultado))

  #SAIR

  if operador == '6' or operador == 'sair':
    print('Obrigado por utilizar a calculadora do mestre')

  opcoes02 = '''
   [1] Não desejo sair 
   [2] Quero continuar

  '''
  print(opcoes02)
  input(opcoes02)

  if opcoes02 == '1':
  print('Obrigado por utilizar a calculadora do mestre')

  else opcoes02 = '2'